# DAY 1 — Understanding & Profiling

In [ ]:
# Dataset Description

The dataset contains customer information collected from four major telecom service providers in India: Airtel, Reliance Jio, Vodafone, and BSNL. It includes 243,553 customer records and multiple demographic, geographic, and telecom usage-related variables. The dataset is designed to analyze customer churn behavior in the telecom industry.

The data contains customer details such as age, gender, state, city, estimated salary, telecom usage patterns, and registration information. It also includes a target variable called churn, which indicates whether a customer has left the telecom service provider or remained active.

The dataset contains both numerical and categorical variables, making it suitable for Exploratory Data Analysis (EDA), customer behavior analysis, churn analysis, and business insight generation. Additionally, the dataset includes a date column (date_of_registration) which enables time-based analysis such as customer onboarding trends and churn patterns over time.

Business Understanding

Customer churn is one of the major business challenges in the telecom industry. Due to intense competition among telecom providers, customers can easily switch from one company to another based on pricing, network quality, internet speed, customer service, or promotional offers.

Telecom companies aim to understand the factors influencing customer churn so they can improve customer retention and reduce revenue loss. Retaining existing customers is generally more cost-effective than acquiring new customers, making churn analysis an important business activity.

This project focuses on analyzing customer demographics, telecom usage behavior, geographic information, and registration patterns to identify factors contributing to customer churn. The insights generated from this analysis can help telecom companies:

identify high-risk customers
improve customer retention strategies
design personalized offers and plans
optimize marketing campaigns
enhance customer satisfaction

The overall goal of the project is to support better business decision-making through data-driven insights into customer churn behavior in the telecom industry.

In [52]:
# import required libraries

import pandas as pd

import numpy as np

# Load data

df = pd.read_csv(r"C:\Users\A S S A U L T\Desktop\eda - project\data\raw\customer_churn_dataset.csv")

In [42]:
# Dataset Overview

df.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,230797,Airtel,M,20.0,Tamil Nadu,Delhi,285677,2023-03-01,2,104752,38,47.0,1687.0,0
1,191986,Vodafone,F,68.0,Uttarakhand,Delhi,679704,2022-08-18,2,71706,43,33.0,991.0,0
2,18779,Vodafone,M,30.0,Goa,Mumbai,837926,2020-04-03,4,137473,-2,12.0,6803.0,0
3,241017,Vodafone,M,22.0,Madhya Pradesh,Chennai,679346,2023-04-21,0,58245,32,11.0,2832.0,0
4,136495,Reliance Jio,M,63.0,Tripura,Bangalore,839738,2021-11-14,4,unknown,68,11.0,5375.0,0

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20100 entries, 0 to 20099
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           20100 non-null  int64
 1   telecom_partner       20100 non-null  str
 2   gender                20100 non-null  str
 3   age                   19897 non-null  float64
 4   state                 19698 non-null  str
 5   city                  19698 non-null  str
 6   pincode               20100 non-null  int64
 7   date_of_registration  20100 non-null  datetime64[us]
 8   num_dependents        20100 non-null  int64
 9   estimated_salary      20100 non-null  str
 10  calls_made            20100 non-null  int64
 11  sms_sent              19700 non-null  float64
 12  data_used             19701 non-null  float64
 13  churn                 20100 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(5), str(5)
memory usage: 2.1 MB

In [44]:
df.describe()

,customer_id,age,pincode,date_of_registration,num_dependents,calls_made,sms_sent,data_used,churn
count,20100.000000,19897.000000,20100.000000,20100,20100.000000,20100.000000,19700.000000,19701.000000,20100.000000
mean,121912.892836,46.002412,549476.896716,2021-09-01 16:14:32.597015,1.977562,51.964726,30.609746,4979.559069,0.200746
min,13.000000,18.000000,100030.000000,2020-01-01 00:00:00,0.000000,-10.000000,-5.000000,-930.000000,0.000000
25%,61057.500000,32.000000,324869.500000,2020-11-01 00:00:00,1.000000,24.000000,11.000000,2456.000000,0.000000
50%,121500.500000,46.000000,547365.000000,2021-08-31 00:00:00,2.000000,49.000000,24.000000,4946.000000,0.000000
75%,182712.250000,60.000000,773477.250000,2022-07-03 00:00:00,3.000000,74.000000,36.000000,7513.000000,0.000000
max,243540.000000,74.000000,999974.000000,2023-05-03 00:00:00,4.000000,1191.000000,2991.000000,10964.000000,1.000000
std,70253.855868,16.441826,259406.336783,NaN,1.410883,59.378471,119.760456,2966.496991,0.400569

In [45]:
df.nunique()

customer_id             20000
telecom_partner             8
gender                      2
age                        57
state                      28
city                        6
pincode                 19797
date_of_registration     1219
num_dependents              5
estimated_salary        18224
calls_made                196
sms_sent                  129
data_used                9224
churn                       2
dtype: int64

In [46]:
#Identify Numerical Columns,Categorical Columns,date columns

numerical_columns = df.select_dtypes(include =['int64','float64']).columns


print("numerical columns:",numerical_columns)

numerical columns: Index(['customer_id', 'age', 'pincode', 'num_dependents', 'calls_made',
       'sms_sent', 'data_used', 'churn'],
      dtype='str')

In [47]:

Categorical_Columns = df.select_dtypes(include =['object','string']).columns

print("categorical columns:",Categorical_Columns)

categorical columns: Index(['telecom_partner', 'gender', 'state', 'city', 'estimated_salary'], dtype='str')

In [48]:

df['date_of_registration'] = pd.to_datetime(df['date_of_registration'],dayfirst=True)
date_columns = df.select_dtypes(include=['datetime64']).columns

print("date columns:",date_columns)

date columns: Index(['date_of_registration'], dtype='str')

In [49]:
#  missing value analysis

Null_values = df.isnull().sum()

print("Null values:",Null_values)

Null values: customer_id               0
telecom_partner           0
gender                    0
age                     203
state                   402
city                    402
pincode                   0
date_of_registration      0
num_dependents            0
estimated_salary          0
calls_made                0
sms_sent                400
data_used               399
churn                     0
dtype: int64

In [50]:
Duplicate_values = df.duplicated().sum()

print("Duplicate values:",Duplicate_values)

Duplicate values: 82