# DATA CLEANING & PREPROCESSING

In [ ]:
import pandas as pd 

import numpy as np

import matplotlib.pyplot as plt 

import seaborn as sns

df = pd.read_csv(r"C:\Users\A S S A U L T\Desktop\eda - project\data\raw\customer_churn_dataset.csv")

df.head()

### Fix Datatypes

In [117]:
# Converted date_of_registration to datetime

df['date_of_registration']  = pd.to_datetime(df['date_of_registration'],dayfirst=True)

print(df['date_of_registration'])

df['estimated_salary'] = pd.to_numeric(df['estimated_salary'], errors='coerce')

0       2023-03-01
1       2022-08-18
2       2020-04-03
3       2023-04-21
4       2021-11-14
           ...
20095   2020-10-23
20096   2022-11-13
20097   2022-07-19
20098   2023-04-23
20099   2021-12-29
Name: date_of_registration, Length: 20100, dtype: datetime64[us]

### Standardize categorical variables

In [13]:
# capitalize all string columns and trim white spaces 

for cols in df.select_dtypes(include=['object', 'string']).columns:
    
    df[cols] = df[cols].str.capitalize().str.strip()

df.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,230797,Airtel,M,20.0,Tamil nadu,Delhi,285677,01-03-2023,2,104752,38,47.0,1687.0,0
1,191986,Vodafone,F,68.0,Uttarakhand,Delhi,679704,18-08-2022,2,71706,43,33.0,991.0,0
2,18779,Vodafone,M,30.0,Goa,Mumbai,837926,03-04-2020,4,137473,-2,12.0,6803.0,0
3,241017,Vodafone,M,22.0,Madhya pradesh,Chennai,679346,21-04-2023,0,58245,32,11.0,2832.0,0
4,136495,Reliance jio,M,63.0,Tripura,Bangalore,839738,14-11-2021,4,Unknown,68,11.0,5375.0,0

In [12]:
# Standardize gender column

df['gender'] = df['gender'].str.upper().str.strip()

# Standardize telecom_partner column

df['telecom_partner'] = (df['telecom_partner'].str.strip().str.title())

df['telecom_partner'] = df['telecom_partner'].replace({'Bsnl': 'BSNL',})

df.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,230797,Airtel,M,20.0,Tamil nadu,Delhi,285677,01-03-2023,2,104752,38,47.0,1687.0,0
1,191986,Vodafone,F,68.0,Uttarakhand,Delhi,679704,18-08-2022,2,71706,43,33.0,991.0,0
2,18779,Vodafone,M,30.0,Goa,Mumbai,837926,03-04-2020,4,137473,-2,12.0,6803.0,0
3,241017,Vodafone,M,22.0,Madhya pradesh,Chennai,679346,21-04-2023,0,58245,32,11.0,2832.0,0
4,136495,Reliance Jio,M,63.0,Tripura,Bangalore,839738,14-11-2021,4,Unknown,68,11.0,5375.0,0

In [119]:
# remove duplicates

df.drop_duplicates(inplace=True)

df.duplicated().sum()

np.int64(0)

### Handle missing values

In [14]:
# identifying nulls

df.isnull().sum()

customer_id               0
telecom_partner           0
gender                    0
age                     203
state                   402
city                    402
pincode                   0
date_of_registration      0
num_dependents            0
estimated_salary          0
calls_made                0
sms_sent                400
data_used               399
churn                     0
dtype: int64

In [128]:
# Handle missing values

# Fill missing values in age column using median

df['age'] = df['age'].fillna(df['age'].median())

# Fill missing values in state column using mode

df['state'] = df['state'].fillna(df['state'].mode()[0]) 

# Fill missing values in city column using mode

df['city'] = df['city'].fillna(df['city'].mode()[0]) 

# Fill missing values in estimated_salary column using median

df['estimated_salary'] = df['estimated_salary'].fillna(df['estimated_salary'].median())

#Fill missing values in sms_sent column using median

df['sms_sent'] = df['sms_sent'].fillna( df['sms_sent'].median())

#Fill missing values in data_used column using median

df['data_used'] = df['data_used'].fillna( df['data_used'].median())

In [129]:
df.isnull().sum()

customer_id             0
telecom_partner         0
gender                  0
age                     0
state                   0
city                    0
pincode                 0
date_of_registration    0
num_dependents          0
estimated_salary        0
calls_made              0
sms_sent                0
data_used               0
churn                   0
dtype: int64

### Outlier Detection using IQR

In [133]:

# OUTLIER DETECTION FOR estimated_salary USING IQR

Q1 = df['estimated_salary'].quantile(0.25)
Q3 = df['estimated_salary'].quantile(0.75)

IQR = Q3 - Q1

LOWER = Q1 - 1.5 * IQR
UPPER = Q3 + 1.5 * IQR

outliers = df[(df['estimated_salary'] < LOWER) | (df['estimated_salary'] > UPPER)]

print(outliers['estimated_salary'])

88       99999999.0
119        545719.0
302      99999999.0
351        599235.0
385        396477.0
            ...
19127      382019.0
19225      415529.0
19878      532383.0
20015      252203.0
20025      252966.0
Name: estimated_salary, Length: 170, dtype: float64

In [132]:
# OUTLIER DETECTION FOR sms_sent USING IQR

Q1 = df['sms_sent'].quantile(0.25)
Q3 = df['sms_sent'].quantile(0.75)

IQR = Q3 - Q1

LOWER = Q1 - 1.5 * IQR
UPPER = Q3 + 1.5 * IQR

outliers = df[(df['sms_sent'] < LOWER) | (df['sms_sent'] > UPPER)]

print(outliers['sms_sent'])

379      1212.0
833      1684.0
957      1456.0
1014     1115.0
1015     1618.0
          ...
19259    1760.0
19685    1339.0
19727    1042.0
19860    1233.0
19884    1200.0
Name: sms_sent, Length: 74, dtype: float64

In [138]:
# “Log transformation was applied to the estimated_salary column to reduce skewness and minimize the impact of extreme outlier values

import numpy as np

df['estimated_salary_log'] = np.log1p(df['estimated_salary'])

In [139]:
# The estimated_salary column was highly right-skewed with extreme values. A log transformation (log1p) was applied to reduce skewness and normalize the distribution. After transformation, the distribution appeared more balanced

In [141]:
df.to_csv(r"C:\Users\A S S A U L T\Desktop\eda - project\data\interim\customer_churn_dataset.csv")